package net.kigawa.kalender

import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.Surface
import androidx.compose.runtime.Composable
import androidx.lifecycle.viewmodel.compose.viewModel
import net.kigawa.kalender.di.startKoin
import net.kigawa.kalender.ui.navigation.AppDestinations
import net.kigawa.kalender.ui.navigation.AppNavHost
import net.kigawa.kalender.ui.theme.KalenderTheme
import net.kigawa.kalender.viewmodel.AuthViewModel
import net.kigawa.kalender.viewmodel.MsAuthState
import org.koin.core.context.startKoin
import org.koin.core.context.stopKoin
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.launch

@Composable
fun App() {
    val viewModel: AuthViewModel = viewModel()
    val googleAuthState by viewModel.googleAuthState.collectAsStateWithLifecycle()
    val msAuthState by viewModel.msAuthState.collectAsStateWithLifecycle()

    val isLoggedIn = googleAuthState is net.kigawa.kalender.data.auth.AuthManager.State.SignedIn ||
                     msAuthState is MsAuthState.SignedIn

    if (!isLoggedIn) {
        Surface {
            AppNavHost(
                googleAuthState = googleAuthState,
                msAuthState = msAuthState,
                onGoogleSignIn = { viewModel.signInWithGoogle() },
                onMsSignIn = { viewModel.signInWithMicrosoft() },
                startDestination = AppDestinations.LOGIN.route,
            )
        }
    } else {
        AppNavHost(
            googleAuthState = googleAuthState,
            msAuthState = msAuthState,
            onGoogleSignIn = { viewModel.signInWithGoogle() },
            onMsSignIn = { viewModel.signInWithMicrosoft() },
            startDestination = AppDestinations.HOME.route,
        )
    }
}

fun main() {
    startKoin()
    // Initialize Compose for Web
    // The actual rendering is done via index.html + main.js generated by webpack
}