apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kalender-api
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
    - hosts:
        - kalender-api.kigawa.net
      secretName: kalender-api-tls
