apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../base

namespace: kigawa-net-kalender

images:
  - name: harbor.kigawa.net/library/kalender-api
    newTag: main-bea69b8d7b7c62f205061e181a6ee018d2a4a2dd

patches:
  - path: ingress-tls-patch.yaml
